site_name: 'dataverse_utils'
docs_dir: 'docs'
nav:
  - Overview: index.md
  - Console utilities: scripts.md
  - Common workflows: common_workflows.md
  - API reference: api_ref.md
  - FAQ: faq.md
  - Windows notes: windows.md
  - Credits: credits.md

extra_css:
  - css/extra.css
markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - codehilite:
      guess_lang: False
      linenums: False
      use_pygments: False
  - attr_list

theme: readthedocs
plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            docstring_style: numpy
            show_source: true
            filters: public
  - search
